apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1
  namespace: flux
spec:
  selector:
    matchLabels:
      app: hello1
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello1
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello1
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello1svc
  namespace: flux
spec:
  selector:
    app: hello1
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: hello1
#   annotations:
#     kubernetes.io/ingress.class: kong
# #    kubernetes.io/tls-acme: "true"
# #    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
# #    ingress.kubernetes.io/secure-backends: "true"
# #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
# #    nginx.ingress.kubernetes.io/auth-type: basic
# #    nginx.ingress.kubernetes.io/auth-secret: frontend-ingressauth
# #    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
# spec:
#   rules:
#   - host: hello1.test.blablal
#     http:
#       paths:
#       - backend:
#           serviceName: hello1svc
#           servicePort: 80
# #  tls:
# #    - secretName: hello.blablabla
# #        - hello.qa.nicosoft.blablabla
